import { Router, type IRouter } from "express";
import healthRouter from "./health";
import webhooksRouter from "./webhooks";
import usersRouter from "./users";
import onboardingRouter from "./onboarding";
import tenantsRouter from "./tenants";
import catalogRouter from "./catalog";
import ordersRouter from "./orders";
import auditRouter from "./audit";
import notificationsRouter from "./notifications";
import adminRouter from "./admin";
import aiRouter from "./ai";
import paymentsRouter from "./payments";
import shiftsRouter from "./shifts";
import printRouter from "./print";
import importRouter from "./import";
import settingsRouter from "./settings";
import woocommerceRouter from "./woocommerce";
import inventoryRouter from "./inventory";
import sessionRouter from "./session";

const router: IRouter = Router();

router.use(healthRouter);
router.use(webhooksRouter);
router.use(usersRouter);
router.use(onboardingRouter);
router.use(tenantsRouter);
router.use(catalogRouter);
router.use(ordersRouter);
router.use(auditRouter);
router.use(notificationsRouter);
router.use(adminRouter);
router.use(aiRouter);
router.use(paymentsRouter);
router.use(shiftsRouter);
router.use(printRouter);
router.use(importRouter);
router.use(settingsRouter);
router.use(woocommerceRouter);
router.use(inventoryRouter);
router.use(sessionRouter);

export default router;
